# templates/postgres-pvc-cleanup-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-postgres-pvc-cleanup-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-postgres-pvc-cleanup-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "pods"]
  verbs: ["list", "delete", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-postgres-pvc-cleanup-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-postgres-pvc-cleanup-account
roleRef:
  kind: Role
  name: {{ .Release.Name }}-postgres-pvc-cleanup-role
  apiGroup: rbac.authorization.k8s.io
