{{- if eq .Values.persistence.pv "local" -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgresql.fullname" . }}-pv
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: postgres-local
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /storage
  # nodeSelector:
  #   role: database
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - database
{{- end }}
