# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_ADMIN_PASSWORD: {{ .Values.postgresql.password | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
