# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: password-reader
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  # resources: ["{{ include "postgresql.fullname" . }}-secret"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["{{ include "postgresql.fullname" . }}-secret"]
---
# this should be updated to have a select or map or similar to template all the acccounts that need access to the postgres password
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: password-reader-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: gitea-db-job-account
  namespace: vcs 
roleRef:
  kind: Role
  name: password-reader
  apiGroup: rbac.authorization.k8s.io
