# templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgresql.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgresql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ include "postgresql.fullname" . }}-config
            - secretRef:
                name: {{ include "postgresql.fullname" . }}-secret
          volumeMounts:
            - name: {{ include "postgresql.fullname" . }}-pv
              mountPath: /var/lib/postgresql/data
              subPath: postgresql-db
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "postgresql.fullname" . }}-pv
      spec:
        accessModes: [ "{{ .Values.persistence.accessMode }}" ]
        storageClassName: postgres-{{ .Values.persistence.pv }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
