# values.yaml
namespace: vcs

gitea:
  image:
    repository: gitea/gitea
    tag: 1.22
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    host: gitea.icosahedron.io
  database:
    type: postgres
    host: postgres-postgresql.db.svc.cluster.local
    port: 5432
    name: gitea
    user: gitea
    password: gitea
  postgresql:
    namespace: db
    admin: homelab
    secretName: postgres-postgresql-secret # Name of the secret containing PostgreSQL passwords
    secretKey: POSTGRES_ADMIN_PASSWORD # Key in the secret for the PostgreSQL admin password

storage:
  pv: "smb"
  size: 10Gi
  storageClass: gitea-sc
  nfs:
    server: x.x.x.x
    path: "/srv/nfs/k8s/nginx"
    accessMode: ReadWriteOnce
  smb:
    share: "//100.127.21.13/Share"
    readOnly: false
    accessMode: ReadWriteMany
