# values.yaml
namespace: vcs

gitea:
  image:
    repository: gitea/gitea
    tag: 1.22
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    host: gitea.icosahedron.dev
  database:
    type: postgres
    host: postgres-postgresql.db.svc.cluster.local
    port: 5432
    name: gitea
    user: gitea
    password: gitea
  postgresql:
    namespace: db
    admin: homelab
    secretName: postgres-postgresql-secret # Name of the secret containing PostgreSQL passwords
    secretKey: POSTGRES_ADMIN_PASSWORD # Key in the secret for the PostgreSQL admin password

storage:
  pv: "nfs"
  size: 10Gi
  accessMode: ReadWriteMany
  nfs:
    server: nfs-server.storage.svc.cluster.local
    path: /
  smb:
    share: "//smb-server.storage.svc.cluster.local/Share"
    readOnly: false

