# values.yaml
gitea:
  image:
    repository: gitea/gitea
    tag: 1.20.0
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    host: gitea.icosahedron.io
  persistence:
    enabled: true
    size: 5Gi
    storageClass: nfs-client
    nfs:
      server: 100.91.158.43
      path: "/srv/nfs/k8s/gitea"
  database:
    type: postgres
    host: postgres-postgresql.db.svc.cluster.local
    port: 5432
    name: gitea
    user: gitea
    password: gitea
  postgresql:
    namespace: db
    secretName: postgres-postgresql # Name of the secret containing PostgreSQL passwords
    secretKey: postgres-password # Key in the secret for the PostgreSQL admin password

