# values.yaml
namespace: web

serviceAccount:
  name: default

storage:
  pv: "nfs"
  size: 10Gi
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: / # "/exports/nginx"
  smb:
    share: "//100.127.21.13/Share"
    readOnly: false
    accessMode: ReadWriteMany

