# templates/db-job-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-db-job-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-db-job-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["{{ .Values.gitea.postgresql.secretName }}"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-db-job-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-db-job-account
roleRef:
  kind: Role
  name: {{ .Release.Name }}-db-job-role
  apiGroup: rbac.authorization.k8s.io
---

