
# templates/ingress.yaml
{{- if .Values.gitea.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gitea-ingress
spec:
  rules:
  - host: {{ .Values.gitea.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-gitea
            port: 
              number: {{ .Values.gitea.service.port }}
{{- end }}

