# templates/pv.yaml
{{ if eq .Values.storage.pv "nfs" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-{{ .Values.storage.pv }}-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  storageClassName: gitea-{{ .Values.storage.pv }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: {{ .Values.storage.nfs.server }}#{{ .Values.storage.nfs.path }}#gitea
    volumeAttributes:
      server: {{ .Values.storage.nfs.server }}
      share: {{ .Values.storage.nfs.path }}
  mountOptions:
    - nfsvers=4.1
{{ end }}
