# PV for an anonymous SMB share
{{ if eq .Values.storage.pv "smb" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-{{ .Values.storage.pv }}-pv
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: gitea-{{ .Values.storage.pv }}
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0644
    - file_mode=0644
    - vers=3.1.1
    - rw
    - guest
    - uid=git
    - gid=git
    - forceuid
    - forcegid
    - noperm
  csi:
    driver: smb.csi.k8s.io
    readOnly: {{ .Values.storage.smb.readOnly }}
    volumeHandle: smb-vol  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: {{ .Values.storage.smb.share }}
{{ end }}
