# templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-{{ .Values.storage.pv }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: gitea-{{ .Values.storage.pv }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  volumeName: gitea-{{ .Values.storage.pv }}-pv

