apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ if eq .Values.persistence.type "nfs" }}nfs-client{{ else }}{{ .Values.persistence.cloudProvider.storageClass }}{{ end }}
  {{- if eq .Values.persistence.type "nfs" }}
  volumeName: {{ .Release.Name }}-gitea-nfs
  {{- end }}

