# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gitea
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.gitea.service.type }}
  ports:
  - port: {{ .Values.gitea.service.port }}
    targetPort: 3000
  selector:
    app: gitea

