# values.yaml
namespace: db

image:
  repository: postgres
  tag: 16.1
  pullPolicy: IfNotPresent

replicaCount: 1

persistence:
  pv: "local"
  storageClass: "postgres-sc"
  accessMode: ReadWriteOnce
  size: 10Gi
  nfs:
    server: x.x.x.x
    path: "/srv/nfs/k8s/postgres"
  smb:
    share: "//100.127.21.13/Share"
    readOnly: false
  local:


service:
  type: ClusterIP
  port: 5432

postgresql:
  username: homelab
  database: homelab
  password: homelab # You should override this in a separate values file
  initdbArgs: "--data-checksums"
  persistence:
    enabled: true
    deletePVCOnUninstall: true  # Set this to false if you want to keep the PVCs
  labels:
    role: database

resources:
  requests:
    cpu: 750m
    memory: 2Gi
  limits:
    cpu: 2
    memory: 4Gi
