apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb
  namespace: smb-test
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.1.1
    - rw
    - guest
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-vol  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: //100.127.21.13/Share
