{{ if eq .Values.storage.pv "nfs" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs
  namespace {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: {{ .Values.storage.nfs.path }}
  mountOptions:
    - nfsvers=4.2
{{ end }}

