apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.persistence.nfs_server }}
    path: "/srv/nfs/k8s/nginx"
  mountOptions:
    - nfsvers=4.2
