apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 100.91.158.43
    path: "/srv/nfs/k8s/nginx"
  mountOptions:
    - nfsvers=4.2
