apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  volumeName: nginx-{{ .Values.storage.pv }}
