# PV for an anonymous SMB share
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb
  namespace: {{ Values.smb.namespace }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.smb.size }}
  accessModes:
    - {{ Values.smb.acessMode }}
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.1.1
    - rw
    - guest
  csi:
    driver: smb.csi.k8s.io
    readOnly: {{ .Values.smb.readOnly }}
    volumeHandle: smb-vol  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: {{ .Values.smb.share }}
