kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.test_storage.name }}
  namespace: {{ .Values.smb.namespace }}
spec:
  accessModes:
    - {{ .Values.test_storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.test_storage.size }}
  volumeName: {{ .Values.test_storage.pv }}
  storageClassName: ""
