kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# One control plane node and three "workers".
#
# While these will not add more real compute capacity and
# have limited isolation, this can be useful for testing
# rolling updates etc.
#
# The API-server and other control plane components will be
# on the control-plane node.
#
# You probably don't need this unless you are testing Kubernetes itself.
featureGates:
  "StatefulSetAutoDeletePVC": true
name: homelab
nodes:
  - role: control-plane
    image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
    labels:
      ingress-ready: true
      nfs-server: true
    extraPortMappings:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
  - role: worker
    image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
    extraMounts:
      - hostPath: /mnt/mac/Users/jaykint/Projects/kubernetes-homelab/storage
        containerPath: /storage
    labels:
      storage: high-capacity
      role: database
  - role: worker
    image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
    labels:
      cpu: high-capacity
    extraMounts:
      - hostPath: /mnt/mac/Users/jaykint/Projects/kubernetes-homelab/storage
        containerPath: /storage
