kind: Service
apiVersion: v1
metadata:
  name: nfs-web
spec:
  ports:
    - port: 80
  selector:
    role: web-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nfs-web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx  # Adjust this if using a different ingress controller
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nfs-web
            port: 
              number: 80

