apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server-nfs-server-provisioner-0
spec:
  capacity:
    storage: 10Gi  # Adjust this as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage
          operator: In
          values:
          - high-capacity