apiVersion: v1
kind: Namespace
metadata:
  name: secret-owner-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: secret-reader-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: secret-owner-namespace
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "secret-reader-namespace"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "secret-reader-namespace"
type: Opaque
data:
  # echo -n secret-value | base64
  SECRET_KEY: c2VjcmV0LXZhbHVl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-reader-deployment-env
  namespace: secret-reader-namespace
  labels:
    app: secret-reader-example-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-reader-example-env
  template:
    metadata:
      labels:
        app: secret-reader-example-env
    spec:
      containers:
      - name: secret-reading-container-env
        image: python
        command: ["/bin/sh","-c"]
        args: ["echo $SECRET_KEY; sleep infinity"]
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: SECRET_KEY
