kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      name: nfs-server
      labels:
        app: nfs-server
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        storage: high-capacity
      containers:
        - name: nfs-server
          {{- if eq .Values.architecture "aarch64" }}
          image: {{ .Values.image.aarch64 }}
          {{- else if eq .Values.architecture "x86_64" }}
          image: {{ .Values.image.x86_64 }}
          {{- else }}
          image: {{ fail "Unknown architecture for NFS server image" }}
          {{- end }}
          env:
            - name: SHARED_DIRECTORY
              value: "/exports"
          volumeMounts:
            - mountPath: /exports
              name: nfs-vol
          securityContext:
            privileged: true
          ports:
            - name: tcp-2049
              containerPort: 2049
              protocol: TCP
            - name: udp-111
              containerPort: 111
              protocol: UDP
      volumes:
        - name: nfs-vol
          hostPath:
            path: /storage  # modify this to specify another path to store nfs share data
            type: DirectoryOrCreate
